name: build
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      ENV_SECRET:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{inputs.ENVIRONMENT }}
    env:
      ENV_SECRET: ${{ secrets.ENV_SECRET }}
      ENV_VAR: ${{ vars.ENV_VAR }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
#      - run: npm install
#      - run: npm run build
      - run: |
          echo 'printing envs'
          env