name: actions-test
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  deploy:
    uses: kurtsteigleder/actions-test/.github/workflows/build.yml@main
    with:
      ENVIRONMENT: ${{github.ref_name}}
    secrets: inherit