name: actions-test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: main
    secrets:
      ENV_SECRET: ${{secrets.ENV_SECRET}}