name: actions-test
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  deploy:
    uses: kurtsteigleder/actions-test/.github/workflows/build.yml@main
    with:
      ENVIRONMENT: main
    secrets:
      ENV_SECRET: ${{secrets.ENV_SECRET}}