name: actions-test
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: ${{github.ref_name}}
    secrets: inherit
    run: |
    echo 'job should be done unless error occurred'
