name: actions-test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: ./.github/workflow-templates/build.yml
    with:
      ENVIRONMENT: main
    secrets:
      ENV_SECRET: ${{secrets.ENV_SECRET}}