name: actions-test
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: ${{github.ref_name}}
    secrets: inherit
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: |
          echo 'this should only print if there was no error'
