name: actions-test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    - uses: kurtsteigleder/actions-test/.github/workflows/build.yml
    - uses: actions/checkout@v3
      with:
        ENVIRONMENT: main
      secrets:
        ENV_SECRET: ${{secrets.ENV_SECRET}}